disabled_rules:
- trailing_whitespace
- static_over_final_class

opt_in_rules:
- empty_count
- empty_string
- force_unwrapping

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 500
    error: 800
    ignore_comment_only_lines: true

# indication of how complicated or "branchy" the logic is
cyclomatic_complexity:
    warning: 10
    error: 20

reporter: "xcode"
